import { ImageRequireSource } from 'react-native';

export const COUNTRIES = [
    'Afghanistan',
    'Albania',
    'Algeria',
    'Andorra',
    'Angola',
    'Antigua_and_Barbuda',
    'Argentina',
    'Armenia',
    'Aruba',
    'Australia',
    'Austria',
    'Azerbaijan',
    'Bahamas',
    'Bahrain',
    'Bangladesh',
    'Barbados',
    'Belarus',
    'Belgium',
    'Belize',
    'Benin',
    'Bhutan',
    'Bolivia',
    'Bosnia_and_Herzegovina',
    'Botswana',
    'Brazil',
    'Brunei',
    'Bulgaria',
    'Burkina_Faso',
    'Burundi',
    'Cambodia',
    'Cameroon',
    'Canada',
    'Cape_Verde',
    'Central_African_Republic',
    'Chad',
    'Chile',
    'China',
    'Colombia',
    'Comoros',
    'Cook_Islands',
    'Costa_Rica',
    'Cote_d\'Ivoire',
    'Croatia',
    'Cuba',
    'Cyprus',
    'Czech_Republic',
    'Democratic_Republic_of_the_Congo',
    'Denmark',
    'Djibouti',
    'Dominica',
    'East_Timor',
    'Ecuador',
    'Egypt',
    'El_Salvador',
    'Equatorial_Guinea',
    'Eritrea',
    'Estonia',
    'Ethiopia',
    'Federated_States_of_Micronesia',
    'Fiji',
    'Finland',
    'France',
    'French_Guiana',
    'Gabon',
    'Georgia',
    'Germany',
    'Ghana',
    'Greece',
    'Greenland',
    'Grenada',
    'Guatemala',
    'Guinea',
    'Guinea-Bissau',
    'Guyana',
    'Haiti',
    'Honduras',
    'Hungary',
    'Iceland',
    'India',
    'Indonesia',
    'Iran',
    'Iraq',
    'Ireland',
    'Israel',
    'Italy',
    'Jamaica',
    'Japan',
    'Jordan',
    'Kazakhstan',
    'Kenya',
    'Kiribati',
    'Kosovo',
    'Kuwait',
    'Kyrgyzstan',
    'Laos',
    'Latvia',
    'Lebanon',
    'Lesotho',
    'Liberia',
    'Libya',
    'Liechtenstein',
    'Lithuania',
    'Luxembourg',
    'Macedonia',
    'Madagascar',
    'Malawi',
    'Malaysia',
    'Maldives',
    'Mali',
    'Malta',
    'Marshall_Islands',
    'Mauritania',
    'Mauritius',
    'Mexico',
    'Moldova',
    'Monaco',
    'Mongolia',
    'Montenegro',
    'Morocco',
    'Mozambique',
    'Myanmar',
    'Namibia',
    'Nauru',
    'Nepal',
    'Netherlands',
    'New_Zealand',
    'Nicaragua',
    'Niger',
    'Nigeria',
    'North_Korea',
    'Norway',
    'Oman',
    'Pakistan',
    'Palau',
    'Palestine',
    'Panama',
    'Papua_New_Guinea',
    'Paraguay',
    'Peru',
    'Philippines',
    'Poland',
    'Portugal',
    'Qatar',
    'Republic_of_the_Congo',
    'Romania',
    'Russia',
    'Rwanda',
    'Saint_Kitts_and_Nevis',
    'Saint_Lucia',
    'Samoa',
    'San_Marino',
    'Sao_Tome_and_Principe',
    'Saudi_Arabia',
    'Senegal',
    'Serbia',
    'Seychelles',
    'Sierra_Leone',
    'Singapore',
    'Slovakia',
    'Slovenia',
    'Solomon_Islands',
    'Somalia',
    'Somaliland',
    'South_Africa',
    'South_Korea',
    'South_Sudan',
    'Spain',
    'Sri_Lanka',
    'Sudan',
    'Suriname',
    'Swaziland',
    'Sweden',
    'Switzerland',
    'Syria',
    'Taiwan',
    'Tajikistan',
    'Tanzania',
    'Thailand',
    'The_Gambia',
    'Togo',
    'Tonga',
    'Trinidad_and_Tobago',
    'Tunisia',
    'Turkey',
    'Turkmenistan',
    'Tuvalu',
    'Uganda',
    'Ukraine',
    'United_Arab_Emirates',
    'United_Kingdom',
    'United_States',
    'Uruguay',
    'Uzbekistan',
    'Vanuatu',
    'Vatican_City',
    'Venezuela',
    'Vietnam',
    'Yemen',
    'Zambia',
    'Zimbabwe'
]

// @ts-ignore

export const flags = {
    Afghanistan: require('@/assets/images/flags/Afghanistan.svg.png'),
    Albania: require('@/assets/images/flags/Albania.svg.png'),
    Algeria: require('@/assets/images/flags/Algeria.svg.png'),
    Andorra: require('@/assets/images/flags/Andorra.svg.png'),
    Angola: require('@/assets/images/flags/Angola.svg.png'),
    Antigua_and_Barbuda: require('@/assets/images/flags/Antigua_and_Barbuda.svg.png'),
    Argentina: require('@/assets/images/flags/Argentina.svg.png'),
    Armenia: require('@/assets/images/flags/Armenia.svg.png'),
    Aruba: require('@/assets/images/flags/Aruba.svg.png'),
    Australia: require('@/assets/images/flags/Australia.svg.png'),
    Austria: require('@/assets/images/flags/Austria.svg.png'),
    Azerbaijan: require('@/assets/images/flags/Azerbaijan.svg.png'),
    Bahamas: require('@/assets/images/flags/Bahamas.svg.png'),
    Bahrain: require('@/assets/images/flags/Bahrain.svg.png'),
    Bangladesh: require('@/assets/images/flags/Bangladesh.svg.png'),
    Barbados: require('@/assets/images/flags/Barbados.svg.png'),
    Belarus: require('@/assets/images/flags/Belarus.svg.png'),
    Belgium: require('@/assets/images/flags/Belgium.svg.png'),
    Belize: require('@/assets/images/flags/Belize.svg.png'),
    Benin: require('@/assets/images/flags/Benin.svg.png'),
    Bhutan: require('@/assets/images/flags/Bhutan.svg.png'),
    Bolivia: require('@/assets/images/flags/Bolivia.svg.png'),
    Bosnia_and_Herzegovina: require('@/assets/images/flags/Bosnia_and_Herzegovina.svg.png'),
    Botswana: require('@/assets/images/flags/Botswana.svg.png'),
    Brazil: require('@/assets/images/flags/Brazil.svg.png'),
    Brunei: require('@/assets/images/flags/Brunei.svg.png'),
    Bulgaria: require('@/assets/images/flags/Bulgaria.svg.png'),
    Burkina_Faso: require('@/assets/images/flags/Burkina_Faso.svg.png'),
    Burundi: require('@/assets/images/flags/Burundi.svg.png'),
    Cambodia: require('@/assets/images/flags/Cambodia.svg.png'),
    Cameroon: require('@/assets/images/flags/Cameroon.svg.png'),
    Canada: require('@/assets/images/flags/Canada.svg.png'),
    Cape_Verde: require('@/assets/images/flags/Cape_Verde.svg.png'),
    Central_African_Republic: require('@/assets/images/flags/Central_African_Republic.svg.png'),
    Chad: require('@/assets/images/flags/Chad.svg.png'),
    Chile: require('@/assets/images/flags/Chile.svg.png'),
    China: require('@/assets/images/flags/China.svg.png'),
    Colombia: require('@/assets/images/flags/Colombia.svg.png'),
    Comoros: require('@/assets/images/flags/Comoros.svg.png'),
    Cook_Islands: require('@/assets/images/flags/Cook_Islands.svg.png'),
    Costa_Rica: require('@/assets/images/flags/Costa_Rica.svg.png'),
    "Côte d'Ivoire": require('@/assets/images/flags/Cote_d\'Ivoire.svg.png'),
    Croatia: require('@/assets/images/flags/Croatia.svg.png'),
    Cuba: require('@/assets/images/flags/Cuba.svg.png'),
    Cyprus: require('@/assets/images/flags/Cyprus.svg.png'),
    Czech_Republic: require('@/assets/images/flags/Czech_Republic.svg.png'),
    Democratic_Republic_of_the_Congo: require('@/assets/images/flags/Democratic_Republic_of_the_Congo.svg.png'),
    Denmark: require('@/assets/images/flags/Denmark.svg.png'),
    Djibouti: require('@/assets/images/flags/Djibouti.svg.png'),
    Dominica: require('@/assets/images/flags/Dominica.svg.png'),
    East_Timor: require('@/assets/images/flags/East_Timor.svg.png'),
    Ecuador: require('@/assets/images/flags/Ecuador.svg.png'),
    Egypt: require('@/assets/images/flags/Egypt.svg.png'),
    El_Salvador: require('@/assets/images/flags/El_Salvador.svg.png'),
    Equatorial_Guinea: require('@/assets/images/flags/Equatorial_Guinea.svg.png'),
    Eritrea: require('@/assets/images/flags/Eritrea.svg.png'),
    Estonia: require('@/assets/images/flags/Estonia.svg.png'),
    Ethiopia: require('@/assets/images/flags/Ethiopia.svg.png'),
    Federated_States_of_Micronesia: require('@/assets/images/flags/Federated_States_of_Micronesia.svg.png'),
    Fiji: require('@/assets/images/flags/Fiji.svg.png'),
    Finland: require('@/assets/images/flags/Finland.svg.png'),
    France: require('@/assets/images/flags/France.svg.png'),
    French_Guiana: require('@/assets/images/flags/French_Guiana.svg.png'),
    Gabon: require('@/assets/images/flags/Gabon.svg.png'),
    Georgia: require('@/assets/images/flags/Georgia.svg.png'),
    Germany: require('@/assets/images/flags/Germany.svg.png'),
    Ghana: require('@/assets/images/flags/Ghana.svg.png'),
    Greece: require('@/assets/images/flags/Greece.svg.png'),
    Greenland: require('@/assets/images/flags/Greenland.svg.png'),
    Grenada: require('@/assets/images/flags/Grenada.svg.png'),
    Guatemala: require('@/assets/images/flags/Guatemala.svg.png'),
    Guinea: require('@/assets/images/flags/Guinea.svg.png'),
    "Guinea-Bissau": require('@/assets/images/flags/Guinea-Bissau.svg.png'),
    Guyana: require('@/assets/images/flags/Guyana.svg.png'),
    Haiti: require('@/assets/images/flags/Haiti.svg.png'),
    Honduras: require('@/assets/images/flags/Honduras.svg.png'),
    Hungary: require('@/assets/images/flags/Hungary.svg.png'),
    Iceland: require('@/assets/images/flags/Iceland.svg.png'),
    India: require('@/assets/images/flags/India.svg.png'),
    Indonesia: require('@/assets/images/flags/Indonesia.svg.png'),
    Iran: require('@/assets/images/flags/Iran.svg.png'),
    Iraq: require('@/assets/images/flags/Iraq.svg.png'),
    Ireland: require('@/assets/images/flags/Ireland.svg.png'),
    Israel: require('@/assets/images/flags/Israel.svg.png'),
    Italy: require('@/assets/images/flags/Italy.svg.png'),
    Jamaica: require('@/assets/images/flags/Jamaica.svg.png'),
    Japan: require('@/assets/images/flags/Japan.svg.png'),
    Jordan: require('@/assets/images/flags/Jordan.svg.png'),
    Kazakhstan: require('@/assets/images/flags/Kazakhstan.svg.png'),
    Kenya: require('@/assets/images/flags/Kenya.svg.png'),
    Kiribati: require('@/assets/images/flags/Kiribati.svg.png'),
    Kosovo: require('@/assets/images/flags/Kosovo.svg.png'),
    Kuwait: require('@/assets/images/flags/Kuwait.svg.png'),
    Kyrgyzstan: require('@/assets/images/flags/Kyrgyzstan.svg.png'),
    Laos: require('@/assets/images/flags/Laos.svg.png'),
    Latvia: require('@/assets/images/flags/Latvia.svg.png'),
    Lebanon: require('@/assets/images/flags/Lebanon.svg.png'),
    Lesotho: require('@/assets/images/flags/Lesotho.svg.png'),
    Liberia: require('@/assets/images/flags/Liberia.svg.png'),
    Libya: require('@/assets/images/flags/Libya.svg.png'),
    Liechtenstein: require('@/assets/images/flags/Liechtenstein.svg.png'),
    Lithuania: require('@/assets/images/flags/Lithuania.svg.png'),
    Luxembourg: require('@/assets/images/flags/Luxembourg.svg.png'),
    Macedonia: require('@/assets/images/flags/Macedonia.svg.png'),
    Madagascar: require('@/assets/images/flags/Madagascar.svg.png'),
    Malawi: require('@/assets/images/flags/Malawi.svg.png'),
    Malaysia: require('@/assets/images/flags/Malaysia.svg.png'),
    Maldives: require('@/assets/images/flags/Maldives.svg.png'),
    Mali: require('@/assets/images/flags/Mali.svg.png'),
    Malta: require('@/assets/images/flags/Malta.svg.png'),
    Marshall_Islands: require('@/assets/images/flags/Marshall_Islands.svg.png'),
    Mauritania: require('@/assets/images/flags/Mauritania.svg.png'),
    Mauritius: require('@/assets/images/flags/Mauritius.svg.png'),
    Mexico: require('@/assets/images/flags/Mexico.svg.png'),
    Moldova: require('@/assets/images/flags/Moldova.svg.png'),
    Monaco: require('@/assets/images/flags/Monaco.svg.png'),
    Mongolia: require('@/assets/images/flags/Mongolia.svg.png'),
    Montenegro: require('@/assets/images/flags/Montenegro.svg.png'),
    Morocco: require('@/assets/images/flags/Morocco.svg.png'),
    Mozambique: require('@/assets/images/flags/Mozambique.svg.png'),
    Myanmar: require('@/assets/images/flags/Myanmar.svg.png'),
    Namibia: require('@/assets/images/flags/Namibia.svg.png'),
    Nauru: require('@/assets/images/flags/Nauru.svg.png'),
    Nepal: require('@/assets/images/flags/Nepal.svg.png'),
    Netherlands: require('@/assets/images/flags/Netherlands.svg.png'),
    New_Zealand: require('@/assets/images/flags/New_Zealand.svg.png'),
    Nicaragua: require('@/assets/images/flags/Nicaragua.svg.png'),
    Niger: require('@/assets/images/flags/Niger.svg.png'),
    Nigeria: require('@/assets/images/flags/Nigeria.svg.png'),
    North_Korea: require('@/assets/images/flags/North_Korea.svg.png'),
    Norway: require('@/assets/images/flags/Norway.svg.png'),
    Oman: require('@/assets/images/flags/Oman.svg.png'),
    Pakistan: require('@/assets/images/flags/Pakistan.svg.png'),
    Palau: require('@/assets/images/flags/Palau.svg.png'),
    Palestine: require('@/assets/images/flags/Palestine.svg.png'),
    Panama: require('@/assets/images/flags/Panama.svg.png'),
    Papua_New_Guinea: require('@/assets/images/flags/Papua_New_Guinea.svg.png'),
    Paraguay: require('@/assets/images/flags/Paraguay.svg.png'),
    Peru: require('@/assets/images/flags/Peru.svg.png'),
    Philippines: require('@/assets/images/flags/Philippines.svg.png'),
    Poland: require('@/assets/images/flags/Poland.svg.png'),
    Portugal: require('@/assets/images/flags/Portugal.svg.png'),
    Qatar: require('@/assets/images/flags/Qatar.svg.png'),
    Republic_of_the_Congo: require('@/assets/images/flags/Republic_of_the_Congo.svg.png'),
    Romania: require('@/assets/images/flags/Romania.svg.png'),
    Russia: require('@/assets/images/flags/Russia.svg.png'),
    Rwanda: require('@/assets/images/flags/Rwanda.svg.png'),
    Saint_Kitts_and_Nevis: require('@/assets/images/flags/Saint_Kitts_and_Nevis.svg.png'),
    Saint_Lucia: require('@/assets/images/flags/Saint_Lucia.svg.png'),
    Samoa: require('@/assets/images/flags/Samoa.svg.png'),
    San_Marino: require('@/assets/images/flags/San_Marino.svg.png'),
    Sao_Tome_and_Principe: require('@/assets/images/flags/Sao_Tome_and_Principe.svg.png'),
    Saudi_Arabia: require('@/assets/images/flags/Saudi_Arabia.svg.png'),
    Senegal: require('@/assets/images/flags/Senegal.svg.png'),
    Serbia: require('@/assets/images/flags/Serbia.svg.png'),
    Seychelles: require('@/assets/images/flags/Seychelles.svg.png'),
    Sierra_Leone: require('@/assets/images/flags/Sierra_Leone.svg.png'),
    Singapore: require('@/assets/images/flags/Singapore.svg.png'),
    Slovakia: require('@/assets/images/flags/Slovakia.svg.png'),
    Slovenia: require('@/assets/images/flags/Slovenia.svg.png'),
    Solomon_Islands: require('@/assets/images/flags/Solomon_Islands.svg.png'),
    Somalia: require('@/assets/images/flags/Somalia.svg.png'),
    Somaliland: require('@/assets/images/flags/Somaliland.svg.png'),
    South_Africa: require('@/assets/images/flags/South_Africa.svg.png'),
    South_Korea: require('@/assets/images/flags/South_Korea.svg.png'),
    South_Sudan: require('@/assets/images/flags/South_Sudan.svg.png'),
    Spain: require('@/assets/images/flags/Spain.svg.png'),
    Sri_Lanka: require('@/assets/images/flags/Sri_Lanka.svg.png'),
    Sudan: require('@/assets/images/flags/Sudan.svg.png'),
    Suriname: require('@/assets/images/flags/Suriname.svg.png'),
    Swaziland: require('@/assets/images/flags/Swaziland.svg.png'),
    Sweden: require('@/assets/images/flags/Sweden.svg.png'),
    Switzerland: require('@/assets/images/flags/Switzerland.svg.png'),
    Syria: require('@/assets/images/flags/Syria.svg.png'),
    Taiwan: require('@/assets/images/flags/Taiwan.svg.png'),
    Tajikistan: require('@/assets/images/flags/Tajikistan.svg.png'),
    Tanzania: require('@/assets/images/flags/Tanzania.svg.png'),
    Thailand: require('@/assets/images/flags/Thailand.svg.png'),
    The_Gambia: require('@/assets/images/flags/The_Gambia.svg.png'),
    Togo: require('@/assets/images/flags/Togo.svg.png'),
    Tonga: require('@/assets/images/flags/Tonga.svg.png'),
    Trinidad_and_Tobago: require('@/assets/images/flags/Trinidad_and_Tobago.svg.png'),
    Tunisia: require('@/assets/images/flags/Tunisia.svg.png'),
    Turkey: require('@/assets/images/flags/Turkey.svg.png'),
    Turkmenistan: require('@/assets/images/flags/Turkmenistan.svg.png'),
    Tuvalu: require('@/assets/images/flags/Tuvalu.svg.png'),
    Uganda: require('@/assets/images/flags/Uganda.svg.png'),
    Ukraine: require('@/assets/images/flags/Ukraine.svg.png'),
    United_Arab_Emirates: require('@/assets/images/flags/United_Arab_Emirates.svg.png'),
    United_Kingdom: require('@/assets/images/flags/United_Kingdom.svg.png'),
    United_States: require('@/assets/images/flags/United_States.svg.png'),
    Uruguay: require('@/assets/images/flags/Uruguay.svg.png'),
    Uzbekistan: require('@/assets/images/flags/Uzbekistan.svg.png'),
    Vanuatu: require('@/assets/images/flags/Vanuatu.svg.png'),
    Vatican_City: require('@/assets/images/flags/Vatican_City.svg.png'),
    Venezuela: require('@/assets/images/flags/Venezuela.svg.png'),
    Vietnam: require('@/assets/images/flags/Vietnam.svg.png'),
    Yemen: require('@/assets/images/flags/Yemen.svg.png'),
    Zambia: require('@/assets/images/flags/Zambia.svg.png'),
    Zimbabwe: require('@/assets/images/flags/Zimbabwe.svg.png')
}
